### PR TITLE
New feature: zoom and pan

### LINKED ISSUE #112: Enable pan/zoom

### PR DESCRIPTION
**Pull request by alxvth**
- New: Enables zoom and pan interactions
- New: Exposes zoom rectangle through a rectangle action such that other plugins can connect to it
- Improved: Adds keybinding to readme

Closes #112

### CODE REVIEW

**Review by ThomasKroes — APPROVED** [review]
Works well on my machine. The only change I'd propose is the use of `RectangleAction` for the `_showBounds` type member. Thus the zoom rectangle can be modified outside of the scatterplot as well (think of coordinated views when comparing embeddings in separate scatter plots).

**Review by ThomasKroes — CHANGES_REQUESTED** [review]
The only change I'd propose is the use of `mv::gui::RectangleAction` for the `_showBounds` type member. Thus the zoom rectangle can be modified outside of the scatterplot as well (think of coordinated views when comparing embeddings in separate scatter plots).

**Comment by alxvth** [comment]
WIP, but will build on CI after https://github.com/ManiVaultStudio/core/pull/561 is merged

**Comment by alxvth** [comment]
Work well, depends on [core/feature/ZoomInPlot](https://github.com/ManiVaultStudio/core/tree/feature/ZoomInPlot)

**Review by ThomasKroes — APPROVED** [review]

**Pull request merged**
